language: node_js

node_js:
  - 18

cache:
  yarn: false
  directories:
    - node_modules

sudo: false

jobs:
  include:
    - stage: Lint
      name: Test lint stage
      script: npm run test:lint
    - stage: Code
      name: Test code stage
      script: npm run test:code
